// Map French country names → flag emoji
const FLAGS: Record<string, string> = {
  "Japon": "🇯🇵",
  "Islande": "🇮🇸",
  "France": "🇫🇷",
  "Égypte": "🇪🇬",
  "Maroc": "🇲🇦",
  "Kenya": "🇰🇪",
  "Sénégal": "🇸🇳",
  "Afrique du Sud": "🇿🇦",
  "États-Unis": "🇺🇸",
  "Canada": "🇨🇦",
  "Mexique": "🇲🇽",
  "Brésil": "🇧🇷",
  "Argentine": "🇦🇷",
  "Pérou": "🇵🇪",
  "Équateur": "🇪🇨",
  "Cuba": "🇨🇺",
  "Allemagne": "🇩🇪",
  "Espagne": "🇪🇸",
  "Italie": "🇮🇹",
  "Grèce": "🇬🇷",
  "Portugal": "🇵🇹",
  "Norvège": "🇳🇴",
  "Thaïlande": "🇹🇭",
  "Inde": "🇮🇳",
  "Népal": "🇳🇵",
  "Arabie saoudite": "🇸🇦",
  "Iran": "🇮🇷",
  "Chine": "🇨🇳",
  "Australie": "🇦🇺",
  "Nouvelle-Zélande": "🇳🇿",
  "Royaume-Uni": "🇬🇧",
  "Irlande": "🇮🇪",
  "Suède": "🇸🇪",
  "Finlande": "🇫🇮",
  "Danemark": "🇩🇰",
  "Pays-Bas": "🇳🇱",
  "Belgique": "🇧🇪",
  "Suisse": "🇨🇭",
  "Autriche": "🇦🇹",
  "Pologne": "🇵🇱",
  "République tchèque": "🇨🇿",
  "Hongrie": "🇭🇺",
  "Roumanie": "🇷🇴",
  "Bulgarie": "🇧🇬",
  "Russie": "🇷🇺",
  "Ukraine": "🇺🇦",
  "Turquie": "🇹🇷",
  "Israël": "🇮🇱",
  "Liban": "🇱🇧",
  "Jordanie": "🇯🇴",
  "Syrie": "🇸🇾",
  "Irak": "🇮🇶",
  "Émirats arabes unis": "🇦🇪",
  "Qatar": "🇶🇦",
  "Pakistan": "🇵🇰",
  "Bangladesh": "🇧🇩",
  "Sri Lanka": "🇱🇰",
  "Indonésie": "🇮🇩",
  "Malaisie": "🇲🇾",
  "Singapour": "🇸🇬",
  "Philippines": "🇵🇭",
  "Vietnam": "🇻🇳",
  "Corée du Sud": "🇰🇷",
  "Corée du Nord": "🇰🇵",
  "Mongolie": "🇲🇳",
  "Algérie": "🇩🇿",
  "Tunisie": "🇹🇳",
  "Libye": "🇱🇾",
  "Nigeria": "🇳🇬",
  "Ghana": "🇬🇭",
  "Éthiopie": "🇪🇹",
  "Tanzanie": "🇹🇿",
  "Ouganda": "🇺🇬",
  "Cameroun": "🇨🇲",
  "Côte d'Ivoire": "🇨🇮",
  "Mali": "🇲🇱",
  "Madagascar": "🇲🇬",
  "Chili": "🇨🇱",
  "Colombie": "🇨🇴",
  "Venezuela": "🇻🇪",
  "Uruguay": "🇺🇾",
  "Paraguay": "🇵🇾",
  "Bolivie": "🇧🇴",
};

export function flagFor(country?: string): string {
  if (!country) return "🏳️";
  return FLAGS[country] ?? "🏳️";
}
